<td style="padding:0 5px;"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                         <tr>
                           <td height="96" align="center"><a href="[field:arcurl /]"> <img src="[field:picname/]" width="150" height="120" border="0" style="border:1px #cccccc solid; padding:2px;" /></a> </td>
                         </tr>
                         <tr>
                           <td align="center" class="f12" height="24"><a href="[field:arcurl /]" title="[field:title /]">[field:title /]</a></td>
                         </tr>
                     </table></td>