<?php
$z[0]=Array("global","",197,224);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",277,304);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("global","",358,385);
$z[2][4]['name']="cfg_basehost";
$z[3]=Array("global","",442,469);
$z[3][4]['name']="cfg_basehost";
$z[4]=Array("global","",585,612);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("global","",888,910);
$z[5][4]['name']="banquan";
$z[6]=Array("global","",952,977);
$z[6][4]['name']="cfg_beian";

?>