<?php
$z[0]=Array("global","",197,224);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",280,307);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("global","",364,391);
$z[2][4]['name']="cfg_basehost";
$z[3]=Array("global","",451,478);
$z[3][4]['name']="cfg_basehost";
$z[4]=Array("global","",596,623);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("global","",906,928);
$z[5][4]['name']="banquan";
$z[6]=Array("global","",970,995);
$z[6][4]['name']="cfg_beian";

?>