<?php
$z[0]=Array("myad","",220,255);
$z[0][4]['name']="innerTopBanner1";
$z[1]=Array("myad","",408,443);
$z[1][4]['name']="innerTopBanner2";
$z[2]=Array("global","",656,681);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("channel","\r\n      	<li><a href='[field:typeurl/]' >[field:typename/]</a></li>\r\n      	",709,895);
$z[3][4]['type']="top";
$z[3][4]['row']="10";
$z[3][4]['currentstyle']="<li><a href='~typelink~' >~typename~</a></li>";
$z[4]=Array("arclist","\r\npicarr[[field:global.autoindex/]]  = \"[field:litpic/]\";\r\n\r\n",1867,1985);
$z[4][4]['flag']="f";
$z[4][4]['row']="5";
$z[4][4]['typeid']="8";
$z[5]=Array("global","",2559,2589);
$z[5][4]['name']="cfg_templeturl";
$z[6]=Array("global","",2920,2950);
$z[6][4]['name']="cfg_templeturl";

?>