<?php
$z[0]=Array("global","",229,261);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",463,488);
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("channel","\r\n      	<li><a href='[field:typeurl/]' >[field:typename/]</a></li>\r\n      	",516,701);
$z[2][4]['type']="top";
$z[2][4]['row']="4";
$z[2][4]['currentstyle']="<li><a href='~typelink~' >~typename~</a></li>";
$z[3]=Array("global","",1039,1071);
$z[3][4]['name']="cfg_templets_skin";

?>