<?php
$z[0]=Array("global","",229,261);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",350,382);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",576,601);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("channel","\r\n      	<li><a href='[field:typeurl/]' >[field:typename/]</a></li>\r\n      	",629,814);
$z[3][4]['type']="top";
$z[3][4]['row']="4";
$z[3][4]['currentstyle']="<li><a href='~typelink~' >~typename~</a></li>";
$z[4]=Array("global","",1128,1160);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",3290,3322);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",3428,3460);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("global","",3566,3598);
$z[7][4]['name']="cfg_templets_skin";
$z[8]=Array("global","",3704,3736);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("global","",4236,4268);
$z[9][4]['name']="cfg_templets_skin";
$z[10]=Array("global","",4319,4351);
$z[10][4]['name']="cfg_templets_skin";

?>